/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Project = IDL.Record({
  'reraApprovalDetails' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'details' : IDL.Text,
  'specialtyFeatures' : IDL.Text,
  'pincode' : IDL.Text,
  'priceBreakdown' : IDL.Text,
  'location' : IDL.Text,
  'connectivityFeatures' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'plotNumber' : IDL.Text,
  'message' : IDL.Text,
});
export const PublicProjectView = IDL.Record({
  'reraApprovalDetails' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'details' : IDL.Text,
  'specialtyFeatures' : IDL.Text,
  'pincode' : IDL.Text,
  'priceBreakdown' : IDL.Text,
  'location' : IDL.Text,
  'connectivityFeatures' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createProject' : IDL.Func([IDL.Text, Project], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'getAllInquiries' : IDL.Func([IDL.Text], [IDL.Vec(Inquiry)], []),
  'getProject' : IDL.Func([], [IDL.Opt(PublicProjectView)], ['query']),
  'getProjectsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
  'getProjectsByPincode' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateProject' : IDL.Func([IDL.Text, Project], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Project = IDL.Record({
    'reraApprovalDetails' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'details' : IDL.Text,
    'specialtyFeatures' : IDL.Text,
    'pincode' : IDL.Text,
    'priceBreakdown' : IDL.Text,
    'location' : IDL.Text,
    'connectivityFeatures' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'plotNumber' : IDL.Text,
    'message' : IDL.Text,
  });
  const PublicProjectView = IDL.Record({
    'reraApprovalDetails' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'details' : IDL.Text,
    'specialtyFeatures' : IDL.Text,
    'pincode' : IDL.Text,
    'priceBreakdown' : IDL.Text,
    'location' : IDL.Text,
    'connectivityFeatures' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createProject' : IDL.Func([IDL.Text, Project], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'getAllInquiries' : IDL.Func([IDL.Text], [IDL.Vec(Inquiry)], []),
    'getProject' : IDL.Func([], [IDL.Opt(PublicProjectView)], ['query']),
    'getProjectsByCity' : IDL.Func([IDL.Text], [IDL.Vec(Project)], ['query']),
    'getProjectsByPincode' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateProject' : IDL.Func([IDL.Text, Project], [], []),
  });
};

export const init = ({ IDL }) => { return []; };